owner: palnabarun
repo: status

sites:
  - name: Kubernetes Hound
    url: https://cs.k8s.io
  - name: Plausible
    url: https://paa.nabarun.dev

status-website:
  cname: status.nabarun.top
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Uptime Monitoring
  introTitle: ""
  introMessage: "Uptime status for services like Kubernetes Hound (cs.k8s.io) and Plausible (paa.nabarun.dev)"
  navbar:
    - title: Home
      href: /
